---
- name: Update Pacman
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Install AUR packages
  aur: 
    name: "{{ item }}" 
    tool: yaourt
  become: false
  with_flattened:
      - "{{ aur_list }}"


- name: Install stuff
  pacman:
    name: "{{ package_list }}"
    state: present
  become: yes

- name: pip2
  pip:
    name: keyring
    executable: pip2
    extra_args: --user
