---
package_list:
  - accountsservice
  - acpi
  - acpid
  - adobe-source-code-pro-fonts
  - alsa-firmware
  - alsa-plugins
  - alsa-tools
  - alsa-utils
  - android-tools
  - android-udev
  - ansible
  - arandr
  - artwork-i3
  - autoconf
  - autofs
  - automake
  - autossh
  - avahi
  - aws-cli
  - b43-fwcutter
  - banner
  - bash
  - bash-completion
  - bind-tools
  - binutils
  - bison
  - blueman
  - bluez-tools
  - bluez-utils
  - bmenu
  - btrfs-progs
  - bzip2
  - calibre
  - cheese
  - chromium
  - clipit
  - cmus
  - coreutils
  - cowsay
  - cpupower
  - crda
  - cronie
  - cryptsetup
  - device-mapper
  - dfc
  - dhclient
  - dhcpcd
  - diffutils
  - dmidecode
  - dmraid
  - dnsmasq
  - docker
  - docker-compose
  - dosfstools
  - downgrade
  - e2fsprogs
  - ecryptfs-utils
  - efibootmgr
  - epdfview
  - evince
  - exfat-utils
  - f2fs-tools
  - fakeroot
  - ffmpeg
  - ffmpegthumbnailer
  - figlet
  - file
  - filesystem
  - findutils
  - firefox
  - flac
  - flashplugin
  - flex
  - freerdp
  - gawk
  - gcc
  - gcc-libs
  - gcolor2
  - gconf
  - gettext
  - gimp
  - gksu
  - glances
  - glibc
  - gnome-alsamixer
  - gnome-keyring
  - gnu-netcat
  - go
  - gparted
  - grep
  - grub
  - gst-libav
  - gst-plugins-bad
  - gst-plugins-base
  - gst-plugins-good
  - gst-plugins-ugly
  - gstreamer
  - gufw
  - gvfs
  - gvfs-afc
  - gvfs-gphoto2
  - gvfs-mtp
  - gvfs-smb
  - gzip
  - haveged
  - hddtemp
  - hexchat
  - htop
  - i2c-tools
  - inetutils
  - intel-ucode
  - inxi
  - iproute2
  - iptables
  - iputils
  - ipw2100-fw
  - ipw2200-fw
  - ipython
  - isousb
  - jfsutils
  - jq
  - json-c
  - keepassxc
  - khal
  - khard
  - less
  - lib32-flex
  - lib32-mesa-demos
  - lib32-vulkan-intel
  - libdvdcss
  - libgpod
  - libreoffice-fresh
  - libspf2
  - libtool
  - libva-mesa-driver
  - libvirt
  - libvncserver
  - licenses
  - lightdm-gtk-greeter-settings
  - linux-firmware
  - linux417
  - linux417-acpi_call
  - linux417-headers
  - linux417-virtualbox-host-modules
  - linux417-zfs
  - logrotate
  - lsb-release
  - lvm2
  - lxappearance
  - lxinput
  - m4
  - maia-console
  - make
  - man-db
  - man-pages
  - manjaro-alsa
  - manjaro-browser-settings
  - manjaro-firmware
  - manjaro-hello
  - manjaro-hotfixes
  - manjaro-i3-settings
  - manjaro-printer
  - manjaro-pulse
  - manjaro-release
  - manjaro-settings-manager-notifier
  - manjaro-system
  - markdown_previewer
  - mdadm
  - memtest86+
  - mesa-demos
  - mhwd
  - mhwd-db
  - mkinitcpio-openswap
  - mlocate
  - mobile-broadband-provider-info
  - moc
  - modemmanager
  - morc_menu
  - mousepad
  - mp3info
  - mpv
  - msmtp
  - msmtp-mta
  - mpv
  - nano
  - ncdu
  - neomutt
  - net-tools
  - netctl
  - network-manager-applet
  - networkmanager
  - networkmanager-dispatcher-ntpd
  - networkmanager-openconnect
  - networkmanager-openvpn
  - networkmanager-pptp
  - networkmanager-vpnc
  - newsboat
  - nfs-utils
  - ninja
  - nmap
  - nodejs
  - nss-mdns
  - ntfs-3g
  - ntp
  - offlineimap
  - open-fuse-iso
  - openresolv
  - openssh
  - os-prober
  - otf-fira-mono
  - p7zip
  - pa-applet
  - pacman
  - pamac
  - patch
  - pavucontrol
  - pciutils
  - pcmanfm
  - pcmciautils
  - pdfjs
  - perl
  - perl-anyevent-i3
  - perl-file-mimeinfo
  - perl-json-xs
  - pkgconf
  - polkit-gnome
  - poppler-data
  - postgresql
  - powertop
  - procps-ng
  - psmisc
  - pulseaudio-bluetooth
  - python-httplib2
  - python-neovim
  - python-netaddr
  - python-pip
  - python-pyflakes
  - python-pyinotify
  - python-virtualenv
  - python-virtualenvwrapper
  - python2-dateutil
  - python2-httplib2
  - python2-jmespath
  - python2-neovim
  - python2-netaddr
  - python2-pip
  - python2-pyinotify
  - python2-websocket-client
  - qt5-styleplugins
  - qt5ct
  - qutebrowser
  - ranger
  - redshift
  - reiserfsprogs
  - remmina
  - riot-desktop
  - rpmextract
  - rsync
  - ruby
  - s-nail
  - samba
  - sbt
  - sbxkb
  - screen
  - screenfetch
  - seahorse
  - sed
  - shadow
  - smartmontools
  - speedtest-cli
  - sudo
  - syncthing
  - syncthing-gtk
  - sysfsutils
  - syslog-ng
  - systemd-sysvcompat
  - tar
  - terminus-font
  - termite
  - terraform
  - texinfo
  - the_silver_searcher
  - tk
  - tlp
  - tmux
  - tpacpi-bat
  - transmission-gtk
  - transmission-remote-gtk
  - tree
  - ttf-bitstream-vera
  - ttf-dejavu
  - ttf-droid
  - ttf-fira-mono
  - ttf-inconsolata
  - ttf-indic-otf
  - ttf-liberation
  - typescript
  - ufw-extras
  - unzip
  - upower
  - usbutils
  - util-linux
  - vagrant
  - vdirsyncer
  - vi
  - vibrancy-colors
  - viewnior
  - virt-install
  - virt-manager
  - virtualbox
  - vlc-nightly
  - volumeicon
  - vulkan-intel
  - w3m
  - weechat
  - which
  - wine
  - winetricks
  - wireshark-cli
  - wireshark-gtk
  - wmutils
  - wpa_supplicant
  - x11-ssh-askpass
  - x86_energy_perf_policy
  - xarchiver
  - xorg-xbacklight
  - xclip
  - xcursor-chameleon-pearl
  - xcursor-maia
  - xdg-su
  - xdg-user-dirs
  - xdg-utils
  - xdotool
  - xf86-input-elographics
  - xf86-input-evdev
  - xf86-input-keyboard
  - xf86-input-libinput
  - xf86-input-mouse
  - xf86-input-void
  - xf86-video-intel
  - xfburn
  - xfce4-power-manager
  - xfsprogs
  - xorg-server
  - xorg-twm
  - xorg-xbacklight
  - xorg-xhost
  - xorg-xinit
  - xorg-xkill
  - xorg-xprop
  - xss-lock
  - xterm
  - yaourt
  - yarn
  - youtube-dl
  - zd1211-firmware
  - zip
  - zsh

aur_list:
  - burpsuite
  - chef-dk
  - leiningen
  - neovim-gtk
  - postman-bin
  - signal-desktop-bin
  - spotify
  - ttf-crosextra
  - urlview
  - yamllint
  - zoom
