---
# first ensure our target directory exists
- name: Ensure target directory exists
  file:
    dest: "/etc/systemd/system/"
    state: directory

- name: systemd files
  become: true
  template:
    src: '{{ item.src }}'
    dest: /etc/systemd/{{ item.path }}
    mode: '{{ item.mode }}'
    owner: "root" 
  with_filetree: ./
  when: item.state == 'file'

- name: turn on the systemd units (System)
  become: true
  systemd: 
    daemon_reload: yes
    enabled: true
    name: "{{ item }}"
  with_items: "{{ system_units }}"

#- name: turn on the systemd units (User)
#  become: false
#  systemd: 
#    enabled: true
#    name: "{{ item }}"
#  with_items: "{{ user_units }}"
#
- name: vdirsyncer.timer
  become: false
  shell: systemctl enable vdirsyncer.timer --user
  args:
    creates: ~/.config/systemd/user/timers.target.wants/vdirsyncer.timer

- name: notmuch.timer
  become: false
  shell: systemctl enable notmuch.timer --user
  args:
    creates: ~/.config/systemd/user/timers.target.wants/notmuch.timer
