---
# first ensure our target directory exists
- name: Ensure target directory exists
  file:
    dest: "/usr/local/bin/"
    state: directory

- name: /usr/local/bin Files
  become: true
  template:
    src: '{{ item.src }}'
    dest: /usr/local/bin/{{ item.path }}
    mode: '{{ item.mode }}'
    owner: "root" 
  with_filetree: ./
  when: item.state == 'file'

